### ISSUE TITLE
The link doesn't work...

### ISSUE THREAD

**Issue by CLUB777ONE** [juanmartinez890/free-ebay-templates#1]
The link doesn't work www.freeebaytemplates.com/app/

**Comment by juanmartinez890** [comment]
Hi, I do not own that domain anymore. You can check out the demo at http://juanjmartinez.me/freeebaytemplates/

**Comment by CLUB777ONE** [comment]
There I can not find a demo. Is the project death?

**Comment by CLUB777ONE** [comment]
very nice thank you
